### ISSUE TITLE
Missing Lapps Artifact

### ISSUE THREAD

**Issue by mhabsaoui** [lappsgrid-services/edu.brandeis.cs.uima.dkpro#2]
Hi,

i've got a missing artifact org.lappsgrid:service-grid-libs:jar:1.1.0 as you can see on following image: 

![capture](https://cloud.githubusercontent.com/assets/18755135/25676811/c083d9a8-3043-11e7-8cc9-4cc5bca01281.PNG)

- Are there any already updated & compiled WAR of lapps wrapped services (dkpro, gate,...) OR any expected releases including all latest updates (versions for maven, Lapps API...) ?

- I'm  eagerly looking for the gate services Converter code source project on GitHub. Is there any existing one ?

-  Is-it  possible to update the github repositories of services projects so they work without modifying anything (versions of lapps.* in pom,...) ?

- Is there any updated wrapping tutorial, cause the one existing has old java api if i'm not wrong ?

- Is  it possible to add nonexistent discriminator categories in the LSEV Vocabulary from source code, or we have to ask Lapps to add it for us  in here:  http://vocab.lappsgrid.org/discriminators.html  ?

`context.put("myToken", "http://example.com/token");`
==>  Does this allow inter-operating with non LSEV Vocab. URI ??
 

Thanks.

**Comment by ksuderman** [comment]
1. Unfortunately there are no pre-compiled binaries available.  Ideally users should be able to run  
  ```
  git clone ...
  mvn package
  ```  
to create the binary.  At least that is the goal.  

2. The Gate converter service lives at https://github.com/oanc/org.anc.lapps.gate.converter-service

3. As mentioned above, it should be possible to build the projects/services without modification.  I will create a pull-request to fix the pom for this project..

4. Not at the moment, but it looks like it is time to update the tutorial code again!

5. There is no automatic way to add URIs to the list of discriminators, but services are free to use any URI they want as a discriminator it is just that no other LAPPS service will understand those URI.  For example, if you have services that produce and consume http://example.com/token annotations then your services can use http://example.com/token.  It is only if you want to send that to another LAPPS service that you would need to do a conversion/mapping.

Suggested updates the discriminators/vocabulary can be made at https://github.com/lapps/vocabulary-pages/issues

In the meantime you should be able to get this project to compile by:
1. Change the parent-pom to version 2.0.2
1. Delete the dependency on the service-grid-libs.

The service-grid-libs was needed before the Service Manager project started deploying their artifacts a Maven repository.  Now that the Service Manager artifacts are on Maven Central this library is no longer needed and the Service Manager dependencies are declared in the updated parent pom.

**Comment by ksuderman** [comment]
Opps, the parent pom to use should be:

```xml
<parent>
    <groupId>org.lappsgrid.maven</groupId>
    <artifactId>war-parent-pom</artifactId>
    <version>2.0.5</version>
</parent>
```
